---
  - name: Install and configure Filebeat
    hosts: webservers
    become: true
    tasks:

    - name: Download Filebeat
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb
      
    - name: Install filebeat
      command: dpkg -i filebeat-7.6.1-amd64.deb
      
    - name: Drop in filebeat-config.yml
      copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml
      
    - name: Enable and configure the system module
      command: filebeat modules enable system
      
    - name: Set up filebeat
      command: filebeat setup
      
    - name: Start filebeat
      command: service filebeat start
      
    - name: Enable Filebeat on system restart
      systemd:
        name: filebeat
        enabled: yes